services:
  - type: web
    name: document-ocr-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_DEBUG
        value: "False"
      - key: PORT
        value: "5000"
    healthCheckPath: /health
    disk:
      name: document-ocr-disk
      mountPath: /opt/render/project/src
      sizeGB: 1